{% set name = "flask-allows" %}
{% set version = "0.6.0" %}
{% set sha256 = "edc38764457a39618fa86994a9d6c1e2f2f95130982ffa47e9899b2ed3619cd2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install -e . --no-deps --ignore-installed
  noarch: python

requirements:
  build:
    - pip
    - python
    - setuptools
  run:
    - python
    - flask

test:
  imports:
    - flask_allows

about:
  home: https://github.com/justanr/flask-allows
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: authorization tool for Flask

  description: |
    Flask-Allows is an authorization tool for Flask inspired by
    django-rest-framework's permissioning system and rest_condition's
    ability to compose simple requirements into more complex ones.
  dev_url: https://github.com/justanr/flask-allows

extra:
  recipe-maintainers:
    - lvoliveira
    - nicoddemus
    - igortg
