travis:
  secure:
    BINSTAR_TOKEN: 27GKhFkVXZ4VbrWb+9mTQ6jo55dKJZQxU86yQFxGnqmieUhU1IMT9Dd/jjRRvK2CKIGNYEO7U5oGldX6sb0TkHA0HNnCW345jcFJXUiwnUz6M5ahRzMNuhb5Cs1MvEI3IiEB4MMb0Ad40WTtPtPmb1DCF2DAR6yuqYU97C7+3RyMx2whrwdUYoZpG2F3a/gjP3yeGwvkwEbT4JEDa5vKk4fr15U1XfiRcOakPZuTfeLTjPkdpH4GMjam93XwSJKQiAaX/enblnJ5ifoGR09z5IJ4KuF6DV+sjsKI+hvQ+bCE9sxHJzCQMamCUcfwS+nD1oSkhF4ZxnAnMIhFfEAV3+7qroob0CRJdaLn+TVNhsFZR9LoKGiFxnKl3YPy7Y7/DKGHNGfK67b+/8tTb+b9jdxZ6906T9AigBv9tApCyxuVVXBhqXkQMbR/rr+bqflALefhQQz5Opkk6Xfjdxe3KCd3DJ72cxY9xTLS+pUj1nvFwY9GLIGgZgExwwWx/qYaIjjmTydhjdlN9n/JtdrB4mVhp6ntLXq27lxqifRzemqy2AgzLx/gyyT2I6E9VAuaMEoertGBh0SZfGi66EbCCuOxRzH8H9Mf4AaaMU47vL1ZJcmhn9v299d76KmhJR/8SK1x+pYjG0KGB+IZkD4ZwivBrxQuOaiGdNV8xv8bDsA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
