travis:
  secure:
    BINSTAR_TOKEN: MShJVfn41OsyLYIrHXM/40UcqmYpae0PHrRhl3E8AKYUuQ/WYuep34PwPLttmARoBkGpvgpBMnGKH/onGnPnpV2shCVrEY5T8sKmYAHMPfF13hg3zZHrIZldd3nY/UzzOc8OOwKTfcZg9qA6FDo5XrWUw7vjNyQo74G5lk6vxm7Tp1DKuumC8zVmiAZGasI0dmHdn29mcYsGfmoVMPiwssgPMod0OJEiyXzvwKixlbGcvTUG5hX1vdVnMscYBZbkyPlZUpY020rZyvxA+9zpo/vYhv9qhik5Ldu7ZxlE0w6NghROXpic2cdeeasE4LR/rwsSJ7nbEiFA9xx40OBKoUa6sI7pSUYy8AhfPPIKz3TtujfbGuZDWiB5j3bQ1gqyZXE9OF2NAnkuMPPtwvJLaUzPQkj+uFsM1HmUwG5ckIKvgdEx5/i4LHQhtHTKq81+xzDt/Y7SPxGc4cf+KyiwRIuL5yWUhqAW5THQMRA9HdxACT0WzEVt6KDgMh8oQuY6KSAnkfyHERG0upH81IGIp87uHtL28Wi0OGrsO+mU14nZIn+L2KKuFGDY1gbanRUl94TecTIiTMUTu8kN5/MgUC/3ZgywgvMyed8s2dG4KaFru+9Yk63SzIoHQWxkcsLFasReuLqrY+yKZ44agi4azA1FICqq2HC50VEBQPZ16E4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
